### ISSUE TITLE
Flutter 3.22 release mode issue

### ISSUE THREAD

**Issue by simonmoser-bluesource** [shubham-gupta-16/multi_image_picker_view#39] opened 2024-06-11 13:01 UTC
When I run the example with Flutter 3.22 in **release** mode I can take/choose multiple images but only the last is shown.
When I delete the last image the previous image is shown. It's like the grid is collapsed to a stack.
With the latest flutter 3.19 it works as expected.

In this test I took 3 images, only one image is shown: 
![IMG_613D51D8158E-1](https://github.com/shubham-gupta-16/multi_image_picker_view/assets/83814228/3872f26a-cf8e-46b8-b025-e4f481410b78)

**Comment by shubham-gupta-16** [comment] 2024-06-22 17:09
Hi @simonmoser-bluesource,

I just investigated the issue and found that this issue is also with the `flutter_reorderable_grid_view: ^4.0.0` package as well. 
Since `multi_image_picker_view` is using `flutter_reorderable_grid_view` for reordering grid view, it happens here as well.

I raised an issue with at `flutter_reorderable_grid_view` repository:
https://github.com/karvulf/flutter-reorderable-grid-view/issues/105

Unfortunately, that repository is not very active (the last release was 16 months ago). I think I should try any alternative for this.

**Comment by simonmoser-bluesource** [comment] 2024-06-24 05:01
@shubham-gupta-16  thanks for looking into this issue. Hopefully 5.0.0 will be released soon.

**Comment by shubham-gupta-16** [comment] 2024-07-02 06:01
`flutter_reorderable_grid_view` released v5.0.0. We need to update this version in `multi_image_pickder_view`.

**Comment by philitell** [comment] 2024-07-30 11:45
Please release new version with `flutter_reorderable_grid_view`v.5.0.1 - this will fix this issue

**Comment by philitell** [comment] 2024-07-30 12:03
I can confirm that the issue is gone with `flutter_reorderable_grid_view`v.5.0.1

Some refactoring is required - e.g. the onReorder-method of ReorderableBuilder (in multi_image_picker_view.dart) might look something like this:
``` 
onReorder: (ReorderedListFunction reorderedListFunction) {
    final List<ImageFile> reorderedList =
        reorderedListFunction(widget.controller.images.toList()) as List<ImageFile>;
    widget.controller.setImageList(reorderedList);
  },

```
MultiImagePickerController does not need a reOrderImages-method anymore. I would suggest a simple method to pass the reordered list to the controller

```
// in MultiImagePickerController:
  void setImageList(List<ImageFile> images) {
    _images.clear();
    _images = images;
    notifyListeners();
  }

```

**Comment by shubham-gupta-16** [comment] 2024-07-31 10:07
I checked, but 5.0.1 doesn't solve the issue.

**Comment by shubham-gupta-16** [comment] 2024-07-31 10:09
It happens with other reorderable plugins as well, i.e. reorderable_grid_view.

I think flutter has made some major changes in overlay handling in version 3.22

**Comment by shubham-gupta-16** [comment] 2024-08-31 10:17
I checked it on Flutter version: `3.24.1` and it works fine. It seems like the issue was with the flutter version: `3.22.*`.

Closing this issue as there is nothing to do with this library.

**Closed by shubham-gupta-16** 2024-08-31 10:17 UTC
Labels: bug, help wanted
